### ISSUE TITLE
it works on android but not on ios

### ISSUE THREAD

**Issue by aprilmintacpineda** [wumke/react-native-immediate-phone-call#10]
- `react-native-immediate-phone-call@1.0.0`
- Using iPhone 6 simulator.

react-native info:

```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.4
  Yarn: Not Found
  npm: 5.8.0
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2
```

**Comment by wumke** [comment]
I never tested it with simulator... (And I advise everyone to test using real devices, simulators are known to do things slightly different!)

When more info is provided we might be able to help, can you post the relevant log lines?

**Comment by aprilmintacpineda** [comment]
I did `log-ios`. There's nothing special showing on the console. Same with the remote debugger

This is what I can see on the terminal when I make a call.

```
Apr 12 17:16:41 mp-mbp-1107 com.apple.CoreSimulator.SimDevice.58A8DF3B-1160-48BF-9E35-3E1BC5335327[37663] (com.apple.videosubscriptionsd[42929]) <Warning>: Service exited with abnormal code: 1
Apr 12 17:16:41 mp-mbp-1107 com.apple.CoreSimulator.SimDevice.58A8DF3B-1160-48BF-9E35-3E1BC5335327[37663] (com.apple.videosubscriptionsd) <Notice>: Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

Let's keep this open. For the meantime, I'll try to run the app on a real device and see if it works there.

**Comment by jaimehing** [comment]
I'm experiencing the same issue. Testing this in a real device. Is there a resolution for this?

EDIT: seems like it doesn't work if the number passed has spaces between. I've removed the spaces and it works in my device

**Comment by wumke** [comment]
@jaimehing Thanks for the feedback, In the next version I'll cut out spaces automatically!

@aprilmintacpineda , was this also your issue? I already closed it because I tought It worked for you since you did not post any thing about real device usage...

**Comment by ananth10** [comment]
I am facing same issue **com.apple.CoreSimulator.SimDevice.ABB10E92-6E85-4E65-9C58-F2909F252859[564] (com.apple.videosubscriptionsd) <Notice>: Service only ran for 0 seconds. Pushing respawn out by 10 seconds.**. please help to resolve this issue
