### ISSUE TITLE
How to use this library 

### ISSUE THREAD

**Issue by kurniawanj26** [wumke/react-native-immediate-phone-call#12]
I just install this library, and try to use it on my app like this :

```Javascript
     
     handleCall(){
        RNImmediatePhoneCall.immediatePhoneCall('0123456789');
    }

    <TouchableOpacity
            onPress={ ()=> this.handleCall()}
    >
```

but I got an error :
![simulator screen shot - iphone 6 - 2018-06-07 at 23 52 54](https://user-images.githubusercontent.com/6804018/41114246-0e99f8c0-6aae-11e8-986c-1f976b591053.png)

**Comment by wumke** [comment]
Did you link (manually or automatically) the module correctly to your native projects?  
(Typical point of failure on 'NativeModules.ModuleName undefined is not an object' errors!)

**Comment by kurniawanj26** [comment]
I run `npm link`

**Comment by wumke** [comment]
Normally you only have to run the 'npm install' to get the dependencies downloaded, then run 'react-native link react-native-immediate-phone-call' to link to the native projects.
