### ISSUE TITLE
More options when initiating call

### ISSUE THREAD

**Issue by amadeus-torwell** [wumke/react-native-immediate-phone-call#13]
Hi, would it possible (in theory) to add more options to the call? I am thinking specifically about activating the loudspeaker by default.

Thanks,
Amadeus

**Comment by wumke** [comment]
I don't know for sure, I've set music and video call audio to speaker before but I don't think this works for a phone call. You can search if parameters can be passed together with the call-urls for iOS and Android... your idea makes sense to me and if possible I would include the feature.

**Comment by wumke** [comment]
Hmmm, according to [https://stackoverflow.com/questions/4545395/is-it-possible-to-use-the-speaker-on-programmatically-initiated-phone-calls](https://stackoverflow.com/questions/4545395/is-it-possible-to-use-the-speaker-on-programmatically-initiated-phone-calls) it cannot be done in iOS...
