### ISSUE TITLE
 Build Tools revision (23.0.1)

### ISSUE THREAD

**Issue by pablo179** [wumke/react-native-immediate-phone-call#14]
i have a problem with version

![deepinscreenshot_select-area_20180806013210](https://user-images.githubusercontent.com/26826353/43700528-8e9820d6-9918-11e8-90fe-ea119c49f81c.png)

**Comment by wumke** [comment]
I know a solution for this, altough I have not yet implemented it... meanwhile you can just update the numbers yourself in your local copy, that works fine.
