### ISSUE TITLE
How to make a call inside our app without phone number?

### ISSUE THREAD

**Issue by saikiranoptisol** [wumke/react-native-immediate-phone-call#22]
Hi, 

In the app (chatting app) that I creating i have calling option. This calling must be initiated to particular user based on the room id. Is it possible with this package. If yes can you provide a sample demo in usage

**Comment by wumke** [comment]
No, this package only initiates phone calls to phone numbers, thats it.
No package will solve this out of the box for a custom app like you need.

FYI: You can search for WebRTC and implement the signaling server yourself, then you can give any phone/room the id you want and call them.
