### ISSUE TITLE
A problem occurred configuring project ':react-native-immediate-phone-call'.

### ISSUE THREAD

**Issue by DamodarSharma** [wumke/react-native-immediate-phone-call#24]
Failed to install the following Android SDK packages as some licences have not been accepted.
     platforms;android-23 Android SDK Platform 23
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html

  Using Android SDK: C:\Users\ANIL\AppData\Local\Android\Sdk

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.2"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 27
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.7'
    distributionUrl = distributionUrl.replace("bin", "all")
}

**Comment by wumke** [comment]
This looks more like a IDE/gradle build error than a library error to me.

Have you looked further into: 'To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.'? 
If this might be a Windows only issue I cannot help since i don't have a windows developing machine...

**Comment by wumke** [comment]
Did you manage to make it work?

**Comment by vickywane** [comment]
cd into ```%android_home%/tools/bin``` and run ```sdkmanager --licenses``` 
This is clearly a problem with your licenses not an error !
