### ISSUE TITLE
Call in background

### ISSUE THREAD

**Issue by guilherme90** [wumke/react-native-immediate-phone-call#27]
Is it possible to put the call screen in the background after starting the call?

Thanks.

**Comment by EHRdev** [comment]
> Is it possible to put the call screen in the background after starting the call?
> 
> Thanks.

hello, could you do it?, I am interested

**Comment by guilherme90** [comment]
Hello.
This is not possible because it is a feature/limitation of Android and NOT of this project (as far as I know)...
