### ISSUE TITLE
Error when trying generating APK

### ISSUE THREAD

**Issue by guilherme90** [wumke/react-native-immediate-phone-call#28]
Hi,

I'm having a problem while trying to generate APK. Someone help me?

---
LOG

> Task :react-native-immediate-phone-call:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':react-native-immediate-phone-call:verifyReleaseResources'.

java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
  error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
  C:\Users\MyUser\Documents\MobileApps\InterfonneApp\node_modules\react-native-immediate-phone-call\android\build\intermediates\res\merged\release\values-v26\values-v26.xml:7: error: resource android:attr/colorError not found.
  C:\Users\MyUser\Documents\MobileApps\InterfonneApp\node_modules\react-native-immediate-phone-call\android\build\intermediates\res\merged\release\values-v26\values-v26.xml:11: error: resource android:attr/colorError not found.
  C:\Users\MyUser\Documents\MobileApps\InterfonneApp\node_modules\react-native-immediate-phone-call\android\build\intermediates\res\merged\release\values-v26\values-v26.xml:15: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
  C:\Users\MyUser\Documents\MobileApps\InterfonneApp\node_modules\react-native-immediate-phone-call\android\build\intermediates\res\merged\release\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  C:\Users\MyUser\Documents\MobileApps\InterfonneApp\node_modules\react-native-immediate-phone-call\android\build\intermediates\res\merged\release\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  C:\Users\MyUser\Documents\MobileApps\InterfonneApp\node_modules\react-native-immediate-phone-call\android\build\intermediates\res\merged\release\values\values.xml:2711: error: resource android:attr/fontStyle not found.
  C:\Users\MyUser\Documents\MobileApps\InterfonneApp\node_modules\react-native-immediate-phone-call\android\build\intermediates\res\merged\release\values\values.xml:2712: error: resource android:attr/font not found.
  C:\Users\MyUser\Documents\MobileApps\InterfonneApp\node_modules\react-native-immediate-phone-call\android\build\intermediates\res\merged\release\values\values.xml:2713: error: resource android:attr/fontWeight not found.
  C:\Users\MyUser\Documents\MobileApps\InterfonneApp\node_modules\react-native-immediate-phone-call\android\build\intermediates\res\merged\release\values\values.xml:2714: error: resource android:attr/fontVariationSettings not found.
  C:\Users\MyUser\Documents\MobileApps\InterfonneApp\node_modules\react-native-immediate-phone-call\android\build\intermediates\res\merged\release\values\values.xml:2715: error: resource android:attr/ttcIndex not found.
  C:\Users\MyUser\Documents\MobileApps\InterfonneApp\node_modules\react-native-immediate-phone-call\android\build\intermediates\res\merged\release\values\values.xml:2796: error: resource android:attr/startX not found.
  C:\Users\MyUser\Documents\MobileApps\InterfonneApp\node_modules\react-native-immediate-phone-call\android\build\intermediates\res\merged\release\values\values.xml:2799: error: resource android:attr/startY not found.
  C:\Users\MyUser\Documents\MobileApps\InterfonneApp\node_modules\react-native-immediate-phone-call\android\build\intermediates\res\merged\release\values\values.xml:2802: error: resource android:attr/endX not found.
  C:\Users\MyUser\Documents\MobileApps\InterfonneApp\node_modules\react-native-immediate-phone-call\android\build\intermediates\res\merged\release\values\values.xml:2805: error: resource android:attr/endY not found.
  C:\Users\MyUser\Documents\MobileApps\InterfonneApp\node_modules\react-native-immediate-phone-call\android\build\intermediates\res\merged\release\values\values.xml:2813: error: resource android:attr/offset not found.
  error: failed linking references.

**Comment by mallikarjunakp** [comment]
I added the following versions to build.gradle 
```
compileSdkVersion 28
buildToolsVersion "28.0.3"
```

It worked

**Comment by guilherme90** [comment]
@mallikarjunakp in _android/app/build.gradle_ i changed follow lines:

`compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.myapp"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }`

And after this, bundle generated succesfully. Thanks for help!

**Comment by guilherme90** [comment]
Thanks ;)

**Comment by wumke** [comment]
Build tools versions can be a real pain in the ass, also migration to AndroidX made me go crazy while getting al npm libs to work with my projects!
Glad you sorted this out!

**Comment by gypsicoder** [comment]
@mallikarjunakp On which build.gradle ? Main project directory->android->build.gradle or react-native-immediate-phone-call directory->android->build.gradle?

I have added as you mentioned in main projects android directory. It didn't worked.
