### ISSUE TITLE
 error: cannot find symbol 

### ISSUE THREAD

**Issue by amithardikar** [wumke/react-native-immediate-phone-call#29]
> Task :app:compileDebugJavaWithJavac FAILED
D:\ReactNativeProjects\phonecall\phonecall\android\app\src\main\java\com\phonecall\MainActivity.java:13: error: cannot find symbol
       RNImmediatePhoneCallPackage.onRequestPermissionsResult(requestCode, permissions, grantResults);                                    ^

**Comment by wumke** [comment]
Is the package correctly linked in the Android project? I've merged some pull requests yesterday, those should fix automatic linking with 'react-native link'... can you try with latest commit immediately from github instead of npm version?

**Comment by amithardikar** [comment]
yes today only i have installed and linked  on my machine

**Comment by amithardikar** [comment]
onRequestPermissionsResult method is not present in my RNImmediatePhoneCallPackage.java

**Comment by wumke** [comment]
Hmmm, I don't have time to investigate right now, but the method is present in the package code in the repository if I'm not mistaken? 

If you find an error and have a solution feel free to make a pull request...

**Comment by amithardikar** [comment]
hey works fine with me after replacing RNImmediatePhoneCallModule.java and RNImmediatePhoneCallPackage.java from your code.thanks for guide and reply .

**Comment by Nitingadhiya** [comment]
@amithardikar @wumke 
can you please let me know, how i fix the issue. I don't understand what you have replaced?

**Comment by wumke** [comment]
@Nitingadhiya try with latest commit from github, npm package might not be up to date...

**Comment by iamamanprajapati** [comment]
@amithardikar @wumke
can you please let me know, how i fix the issue. I don't understand what you have replaced?
