### ISSUE TITLE
Error: Unable to find symbol

### ISSUE THREAD

**Issue by alveshelio** [wumke/react-native-immediate-phone-call#32]
Hi,

Before everything, I'd like to thank you for the effort you've put in building this module.

Also, I've already read the previous issue with this same error but I don't see a solution to my problem since from what the other user said, Instead of using RNImmediatePhoneCallModule he used RNImmediatePhoneCallPackage, however I've followed the readme and it says to use RNImmediatePhoneCallPackage.

I've double checked the installation process and I have everything similar with your readme.

This is the error I'm getting

```
../MainActivity.java:45: error: cannot find symbol
          RNImmediatePhoneCallPackage.onRequestPermissionsResult(requestCode, permissions, grantResults); // very important event callback
                                     
  symbol:   method onRequestPermissionsResult(int,String[],int[])
  location: class RNImmediatePhoneCallPackage
Note: .../MainApplication.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
```

I'm using react-native 0.59.10

Am I missing something? How could I solve this issue?

Thank you

**Comment by alveshelio** [comment]
I just found the issue. You've actually committed changes on January on GitHub but you've actually never published the package on NPM so your last changes are not available on NPM. The work around was to change the package.json file and replace the version with the pack to the last commit on GitHub like so `"react-native-immediate-phone-call": "wumke/react-native-immediate-phone-call#97066b8ab95e6118b1bcd40bf70a4e8146f47150",`

Do you think you can publish this on NPM?

Thanks

**Comment by wumke** [comment]
See https://github.com/wumke/react-native-immediate-phone-call/issues/30
