### ISSUE TITLE
Nothing happens after calling the function to initiate call

### ISSUE THREAD

**Issue by adefemi171** [wumke/react-native-immediate-phone-call#42]
Hello, tried out this package and I followed every step from the README.

import React from 'react';
import RNImmediatePhoneCall from 'react-native-immediate-phone-call';
import { Button } from 'react-native';
...........
const testCall = () => {
  RNImmediatePhoneCall.immediatePhoneCall("08107804084");
} 
.......

<Button title="Call here" onPress={testCall} />

After clicking on this button, nothing happens and I tried logging out if there was any error but nothing shows as the output as well..

**Comment by adefemi171** [comment]
I think I figured out what the issue is, might be making a PR to the docs

**Comment by jonybar9** [comment]
@adefemi171  Did you figure it out?
We'd love to know how did you solve it

**Comment by adefemi171** [comment]
@jonybar9 what i did different was to put the number in a variable and then use the variable
