### ISSUE TITLE
Getting 'null is not an object' when trying to call

### ISSUE THREAD

**Issue by marcopacurariu3** [wumke/react-native-immediate-phone-call#43]
Hello!

I searched a lot on GitHub and StackOverflow regarding this issue, but I still didn't manage to get an answer. The closest I could get was finding this issue: [https://github.com/wumke/react-native-immediate-phone-call/issues/11?fbclid=IwAR1_MFthP1g28L_kAJqFyy9xkuyonCHFDkoNTaTnjKWwC8HY__PjGAxS7sg](url)

What actually happens: I am using Expo SKD 36, which is based on React Native 0.61.4. After I added the dependency to react-native-immediate-phone-call library, by using:

_npm install react-native-immediate-phone-call --save
react-native link react-native-immediate-phone-call_

I only manage to get this error:
**null is not an object ...evaluating '_reactNative.NativeModules.RNImmediatePhoneCall.immediatePhoneCall**

Did anyone managed to make this library work with Expo? Any help would be very much appreciated.

Thanks a lot!

Attached an image with the logs: [https://ibb.co/6ZvW6Cf](url)

**Comment by marcopacurariu3** [comment]
Ehm... No one? :)

**Comment by tomasz89nowak** [comment]
I met this issue too. I couldn't make it work with managed app, but it works after ejecting and linking manually.

**Comment by marcopacurariu3** [comment]
Thank you very much for the answer and confirmation that the same behavior occurred for you, too. However, it's the first time I'm using React/Expo, so I am not sure how you suggest I should do. Can you give me more input what do you mean with "ejecting and linking manually"? 

Thank you!

Edit: I found into the documentation, I think you refer on this: [https://docs.expo.io/expokit/eject/?redirected](url)

**Comment by tomasz89nowak** [comment]
> Thank you very much for the answer and confirmation that the same behavior occurred for you, too. However, it's the first time I'm using React/Expo, so I am not sure how you suggest I should do. Can you give me more input what do you mean with "ejecting and linking manually"?
> 
> Thank you!
> 
> Edit: I found into the documentation, I think you refer on this: [https://docs.expo.io/expokit/eject/?redirected](url)

Exactly. If You want to use this lib you probably have to eject (switch from managed workflow to bare), but it has serious consequences and should be done only if really necessary.

**Comment by wumke** [comment]
I have never tested with non-ejected apps... but I assume that when using third party libs everyone ejects anyway?
Short answer, you need to eject to use this lib :-)
