### ISSUE TITLE
IOS opening confirm popup for call 

### ISSUE THREAD

**Issue by sagardeveloper** [wumke/react-native-immediate-phone-call#44]
It behaves  like Simple react native Linking call. 
I need to call immediately, how can it be possible?

**Comment by zishon89us** [comment]
It calls immediately i.e. when `RNImmediatePhoneCall.immediatePhoneCall('xxxXXXXxxx');` is invoked it'll open the native phone dialing to `xxxXXXXxxx` phone number. I have just tried.

**Comment by sagardeveloper** [comment]
Why It opens native Dialer, I should call directly. It works on android but
not in IOS

**Comment by Abdelalim-dev** [comment]
From the doc of this module

> Apple always asks confirmation since the last iOS updates...)

It seems that it is not avoidable on iOS

**Comment by wumke** [comment]
What @Abdelalim-dev said... when this lib was created it was still possible on iOS... but not much later they blocked it.
