### ISSUE TITLE
Does react-native-immediate-phone-call disable network connection when make a phone call

### ISSUE THREAD

**Issue by conganwoz** [wumke/react-native-immediate-phone-call#46]
Hi guy!
i just use react-native-immediate-phone-call (RNIC) for 3 months. After a phone call, my app will send a network request to save info about the call on the server, But my users usually (about 30%) get Network error like  this image below. Before using RNIC , i just used Linking of expo and almost requests are called OK.

![Screen Shot 2021-12-07 at 10 30 17](https://user-images.githubusercontent.com/42475170/144961109-f9e6e752-262f-4475-9b0a-b9a8fff97249.png)

please let me know whether RNIC could block network when make a call. If that how can i keep the network stable through the call
Thank you.

**Comment by wumke** [comment]
The app itself does not disable anything, in case you encounter issues you should search at OS level i think...
